services:
  next-plaid:
    image: ghcr.io/lightonai/next-plaid:cpu-1.1.1
    ports:
      - "8080:8080"
    volumes:
      - .data/indices:/data/indices
      - .data/huggingface:/data/huggingface
    environment:
      - HF_HOME=/data/huggingface
      - HF_TOKEN=${HF_TOKEN}
    command: --host 0.0.0.0 --port 8080 --index-dir /data/indices --model lightonai/GTE-ModernColBERT-v1 --int8 --parallel 14 --batch-size 2

  postgres:
    image: postgres:18
    ports:
      - "5432:5432"
    volumes:
      - .data/postgres:/var/lib/postgresql/18/data
    environment:
      - POSTGRES_USER=speeches
      - POSTGRES_PASSWORD=speeches
      - POSTGRES_DB=speeches
